### ISSUE TITLE
Block Ghosting: Graphite Schist

### ISSUE THREAD

**Issue by Hacker6329** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#119]
I'm creating a modpack based on Sky Odyssey and other mods that i'm adding. I don't know why but when i try to break a graphite schist it disappear without dropping anything and if I try to walk on it it glitch.
This is the error when i attempt to break a graphite schist:
[Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$BreakEvent@5a5fe8bd:
java.lang.NullPointerException: null
        at net.minecraft.advancements.PlayerAdvancements.func_192743_a(PlayerAdvancements.java:379) ~[np.class:?]
        at net.minecraft.advancements.PlayerAdvancements.func_192747_a(PlayerAdvancements.java:371) ~[np.class:?]
        at com.hbm.main.AdvancementManager.hasAdvancement(AdvancementManager.java:144) ~[AdvancementManager.class:?]
        at com.hbm.main.ModEventHandler.blockBreak(ModEventHandler.java:904) ~[ModEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1401_ModEventHandler_blockBreak_BreakEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:851) [ForgeHooks.class:14.23.5.2855]
        at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:283) [or.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:154) [or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:693) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
        at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_291]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
[17:30:01] [Server thread/ERROR] [FML]: Index: 15 Listeners:
[17:30:01] [Server thread/ERROR] [FML]: 0: HIGHEST
[17:30:01] [Server thread/ERROR] [FML]: 1: ASM: Block{minecraft:air} tryBreakBlock(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 2: NORMAL
[17:30:01] [Server thread/ERROR] [FML]: 3: ASM: class thaumcraft.common.lib.events.ToolEvents breakBlockEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 4: ASM: class crazypants.enderio.base.item.spawner.BrokenSpawnerHandler onBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 5: ASM: class p455w0rdslib.LibEvents blockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 6: ASM: class p455w0rd.ae2wtlib.init.LibEvents onBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 7: ASM: class WayofTime.bloodmagic.util.handler.event.StatTrackerHandler blockBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 8: ASM: class com.zeitheron.hammercore.event.vanilla.TileHandler breakBlock(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 9: ASM: cofh.core.proxy.EventHandler@2557845c handleBlockBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 10: ASM: crafttweaker.mc1120.events.CommonEventHandler@7ec1e3b9 onBlockBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 11: ASM: class team.chisel.common.item.ChiselController onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 12: ASM: vazkii.quark.tweaks.feature.HoeSickle@3febada5 onBlockBroken(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 13: ASM: com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeListener@36158b08 onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 14: ASM: com.rwtema.extrautils2.modcompat.XUTrait$TraitExperience@30c9796b onMine(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 15: ASM: com.hbm.main.ModEventHandler@10f7e7bb blockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 16: ASM: class mcjty.rftools.blocks.blockprotector.BlockProtectorEventHandlers onBlockBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 17: ASM: slimeknights.tconstruct.tools.traits.TraitEstablished@50c1e706 onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 18: ASM: net.blay09.mods.kleeslabs.KleeSlabs@679af5ad onBreakBlock(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 19: ASM: romelo333.notenoughwands.ForgeEventHandlers@7971d3c6 onBlockBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 20: ASM: lumien.quickleafdecay.QuickLeafDecay@6ee040a0 breakBlock(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 21: ASM: com.bloodnbonesgaming.triumph.events.TEventHandler@78460316 onPlayerBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 22: ASM: class com.enderio.core.common.handlers.XPBoostHandler handleBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 23: ASM: extracells.util.ExtraCellsEventHandler@2d3b9de3 onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 24: ASM: net.geforcemods.securitycraft.SCEventHandler@3ac63bd6 onBlockBroken(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 25: ASM: net.geforcemods.securitycraft.SCEventHandler@3ac63bd6 onBlockEventBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 26: ASM: slimeknights.tconstruct.tools.TraitEvents@549e6670 blockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 27: ASM: zmaster587.advancedRocketry.event.CableTickHandler@2db33181 onBlockBroken(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/ERROR] [FML]: 28: LOWEST
[17:30:01] [Server thread/ERROR] [FML]: 29: ASM: blusunrize.immersiveengineering.common.EventHandler@3369f224 breakLast(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:30:01] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_291]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
Caused by: java.lang.NullPointerException
        at net.minecraft.advancements.PlayerAdvancements.func_192743_a(PlayerAdvancements.java:379) ~[np.class:?]
        at net.minecraft.advancements.PlayerAdvancements.func_192747_a(PlayerAdvancements.java:371) ~[np.class:?]
        at com.hbm.main.AdvancementManager.hasAdvancement(AdvancementManager.java:144) ~[AdvancementManager.class:?]
        at com.hbm.main.ModEventHandler.blockBreak(ModEventHandler.java:904) ~[ModEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1401_ModEventHandler_blockBreak_BreakEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:851) ~[ForgeHooks.class:14.23.5.2855]
        at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:283) ~[or.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:154) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:693) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
        at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_291]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more

**Comment by Hacker6329** [comment]
Oh i forgot, this is the file with the mods list.
[mods.txt](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/files/6802636/mods.txt)
