### ISSUE TITLE
1.6.0 Broken recipe #1?

### ISSUE THREAD

**Issue by x0reaxeax** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#140]
Never seen the word Java in my life before, but maybe this counts as a broken recipe?

```
java.lang.NullPointerException
    at net.minecraft.world.WorldProvider.getSeed(WorldProvider.java:522)
    at net.minecraft.world.World.getSeed(World.java:3500)
    at com.hbm.crafting.handlers.MKUCraftingHandler.generateRecipe(MKUCraftingHandler.java:47)
    at com.hbm.crafting.handlers.MKUCraftingHandler.matches(MKUCraftingHandler.java:28)
    at net.minecraft.item.crafting.CraftingManager.findMatchingRecipe(CraftingManager.java:213)
    at mekanism.common.integration.OreDictManager.addSawmillLog(OreDictManager.java:477)
    at mekanism.common.integration.OreDictManager.addLogRecipes(OreDictManager.java:465)
    at mekanism.common.integration.OreDictManager.init(OreDictManager.java:49)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_389_OreDictManager_init_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
    at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
    at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Unknown Source)
```

Thanks for 1.6.0 I love you ❤️

**Comment by Drillgon200** [comment]
Kind of. It's technically mekanism's fault, but I can fix it from my end.

**Comment by x0reaxeax** [comment]
You're amazing! Closing this :)
