### ISSUE TITLE
every world randomly crashing after while after loading

### ISSUE THREAD

**Issue by jakbes** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#180]
in logs: 
at com.hbm.blocks.machine.MachineBattery.setDefaultFacing(MachineBattery.java:75)
at com.hbm.blocks.machine.MachineBattery.func_176213_c(MachineBattery.java:54)
at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
at net.minecraft.world.World.func_180501_a(World.java:343)
just a billion of these

**Comment by TheForge129** [comment]
Log seems identical to #179...
Looks like Bob fucked up in some way with the energy update, I'd recommend
waiting until he figures it out

**Comment by Drillgon200** [comment]
This isn't bob's fault and I don't think it's mine either. There's some coremod that changes the way setting block states work, but I forgot what it was. The battery's code is exactly the same as one of the vanilla machines.
