### ISSUE TITLE
ok so the even numbered releases are cursed

### ISSUE THREAD

**Issue by TheForge129** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#19]
java.lang.NullPointerException: Ticking block entity
	at com.hbm.forgefluid.FluidContainerRegistry.getFluidFromItem(FluidContainerRegistry.java:29)
	at com.hbm.tileentity.machine.TileEntityMachineChemplant.inputValidForTank(TileEntityMachineChemplant.java:459)
	at com.hbm.tileentity.machine.TileEntityMachineChemplant.func_73660_a(TileEntityMachineChemplant.java:256)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

Can't even break the chemical plant. It crashes as soon as i load the world

**Comment by TheForge129** [comment]
Fixed by enabling the Forge option to delete erroring Entities and TileEntities
