### ISSUE TITLE
it's much much bigger than i thought

### ISSUE THREAD

**Issue by TheForge129** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#23]
heavy oil and bitumen are also broken in chemical plants, if i were you i would just check every single fluid to make sure they're not broken

also water isn't broken
same error report: 
java.lang.NullPointerException: Ticking block entity
	at com.hbm.forgefluid.FluidContainerRegistry.getFluidFromItem(FluidContainerRegistry.java:29)
	at com.hbm.tileentity.machine.TileEntityMachineChemplant.inputValidForTank(TileEntityMachineChemplant.java:459)
	at com.hbm.tileentity.machine.TileEntityMachineChemplant.func_73660_a(TileEntityMachineChemplant.java:256)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

:/

**Comment by TheForge129** [comment]
Full list of broken things:
-Steam
-Coolant
-Crude oil
-Heavy oil
-Bitumen
-Industrial oil
-Heating oil'
-Reclaimed industrial oil
At this point i got bored of testing, i'm just gonna guess that it's every non-vanilla fluid
(And it's only the chemical plant that's broken

**Comment by Drillgon200** [comment]
They're all the same bug, no need to test it more.

**Comment by Drillgon200** [comment]
Fixed.

**Comment by TheForge129** [comment]
Quick question, could you compile (and release) the new version now? (Because this fix is incredibly important for the mod's functionality)
