### ISSUE TITLE
one last issue: crash with java.util.ConcurrentModificationException at com.hbm.tileentity.conductor.tileentityffductbasemk2

### ISSUE THREAD

**Issue by TheForge129** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#4]
crashlog:
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
	at net.minecraft.world.World.func_147448_a(World.java:1949)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:856)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_175625_s(World.java:2402)
	at com.hbm.tileentity.conductor.TileEntityFFDuctBaseMk2.joinOrMakeNetwork(TileEntityFFDuctBaseMk2.java:196)
	at com.hbm.tileentity.conductor.TileEntityFFDuctBaseMk2.onLoad(TileEntityFFDuctBaseMk2.java:110)
	at net.minecraft.world.World.func_175700_a(World.java:1924)
	at net.minecraft.world.World.func_147448_a(World.java:1951)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:856)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:186)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Drillgon200** [comment]
Can you reproduce that? What were you doing when that happened?

**Comment by TheForge129** [comment]
@Drillgon200 I can reproduce by simply entering the world. I have absolutely no clue what entity is causing it

**Comment by Drillgon200** [comment]
I don't know what's causing this either. All I'm doing is getting a tile entity, but apparently you can't do that in the tile entity init? I tried leaving and joining a world with a lot of pipes several times and didn't get this error.

**Comment by TheForge129** [comment]
hmm... it was the same world where the missile launch pad crashed the game... and the pipes lost their fluid identifier after an update from 1.3.3a... that may be the issue, but if not, i have no idea

**Comment by Drillgon200** [comment]
Maybe, I haven't been able to replicate it on a new world with the latest version.
