### ISSUE TITLE
B93 energy mod vs euphemium armor crashes the game

### ISSUE THREAD

**Issue by abel1502** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#55]
I was trying to conduct an experiment and found out that shooting at a forcefield from a B93 energy mod and having the projectile reflected at oneself (in survival and wearing a full set of euphemium armor) reliably (two tests) crashes the game with:
```
The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Ticking entity
Exit code: -1
```
I believe this is not supposed to happen, although I'm unaware of what should (That was the purpose of the experiment I was conducting). I'm also attaching a detailed crash log. I was using the last version of 1.12.2 hbm at that point. If a bug report should include something else, please tell me what.

```
[22:42:51] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.World.func_189509_E(World.java:225) ~[amu.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:905) ~[amu.class:?]
	at com.hbm.entity.projectile.EntityModBeam.func_70071_h_(EntityModBeam.java:343) ~[EntityModBeam.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1996) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1958) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1762) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
[22:42:52] [Server thread/ERROR]: This crash report has been saved to: D:\Games\CurseForge\Minecraft\Instances\Military\crash-reports\crash-2021-02-28_22.42.51-server.txt
[22:42:52] [Server thread/INFO]: Stopping server
[22:42:52] [Server thread/INFO]: Saving players
[22:42:52] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  weaponlib (mw_2.0-0.4.4.6_mc1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 2/28/21 10:42 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.world.World.func_189509_E(World.java:225)
	at net.minecraft.world.World.func_180495_p(World.java:905)
	at com.hbm.entity.projectile.EntityModBeam.func_70071_h_(EntityModBeam.java:343)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.World.func_189509_E(World.java:225)
	at net.minecraft.world.World.func_180495_p(World.java:905)
	at com.hbm.entity.projectile.EntityModBeam.func_70071_h_(EntityModBeam.java:343)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: hbm:entity_mod_beam (com.hbm.entity.projectile.EntityModBeam)
	Entity ID: 1413
	Entity Name: entity.entity_mod_beam.name
	Entity's Exact location: -2261.52, 1.78, -726.40
	Entity's Block location: World: (-2262,1,-727), Chunk: (at 10,0,9 in -142,-46; contains blocks -2272,0,-736 to -2257,255,-721), Region: (-5,-2; contains chunks -160,-64 to -129,-33, blocks -2560,0,-1024 to -2049,255,-513)
	Entity's Momentum: 0.88, 0.04, -4.41
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: 3 (Creative)
	All players: 1 total; [EntityPlayerMP['abel1502'/1234, l='3 (Creative)', x=-2261.52, y=1.00, z=-728.08]]
	Chunk stats: ServerChunkCache: 368 Drop: 0
	Level seed: 654162174516802385
	Level generator: ID 07 - quark_realistic, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-2263,1,-726), Chunk: (at 9,0,10 in -142,-46; contains blocks -2272,0,-736 to -2257,255,-721), Region: (-5,-2; contains chunks -160,-64 to -129,-33, blocks -2560,0,-1024 to -2049,255,-513)
	Level time: 231505 game time, 35187 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 105168 (now: false), thunder time: 45993 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1821494192 bytes (1737 MB) / 5395447808 bytes (5145 MB) up to 5637144576 bytes (5376 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6048m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 10, allocated: 22, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 105 mods loaded, 105 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version                  | Source                                        | Signature                                |
	|:------ |:-------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                  | 9.42                     | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2855             | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | opencomputers|core   | 1.7.5.192                | minecraft.jar                                 | None                                     |
	| LCHIJA | srm-hooks            | 1.12.2-1.0.0             | minecraft.jar                                 | None                                     |
	| LCHIJA | securitycraft        | v1.8.21                  | [1.12.2] SecurityCraft v1.8.21.jar            | None                                     |
	| LCHIJA | actuallyadditions    | 1.12.2-r152              | ActuallyAdditions-1.12.2-r152.jar             | None                                     |
	| LCHIJA | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | actuallybaubles      | 1.1                      | ActuallyBaubles-1.12-1.1.jar                  | None                                     |
	| LCHIJA | buildcraftlib        | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcraftcore       | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcraftfactory    | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcrafttransport  | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcraftsilicon    | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | additionalpipes      | 6.0.0.8                  | additionalpipes-6.0.0.8.jar                   | None                                     |
	| LCHIJA | akashictome          | 1.2-12                   | AkashicTome-1.2-12.jar                        | None                                     |
	| LCHIJA | jei                  | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCHIJA | appleskin            | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                   | None                                     |
	| LCHIJA | ctm                  | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                     | None                                     |
	| LCHIJA | appliedenergistics2  | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar          | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | morphtool            | 1.2-21                   | Morph-o-Tool-1.2-21.jar                       | None                                     |
	| LCHIJA | quark                | r1.6-179                 | Quark-r1.6-179.jar                            | None                                     |
	| LCHIJA | autoreglib           | 1.3-32                   | AutoRegLib-1.3-32.jar                         | None                                     |
	| LCHIJA | blockcraftery        | 1.12.2-1.3.1             | blockcraftery-1.12.2-1.3.1.jar                | None                                     |
	| LCHIJA | buildcraftbuilders   | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | crafttweaker         | 4.1.20                   | CraftTweaker2-1.12-4.1.20.624.jar             | None                                     |
	| LCHIJA | ic2                  | 2.8.170-ex112            | industrialcraft-2-2.8.170-ex112.jar           | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | buildcraftcompat     | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcraftenergy     | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcraftrobotics   | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | catwalks             | 1.12.2-4.0.45            | catwalks-1.12.2-4.0.45.jar                    | None                                     |
	| LCHIJA | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| LCHIJA | chesttransporter     | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar             | None                                     |
	| LCHIJA | chisel               | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                  | None                                     |
	| LCHIJA | clumps               | 3.1.2                    | Clumps-3.1.2.jar                              | None                                     |
	| LCHIJA | codechickenlib       | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | compactmachines3     | 3.0.18                   | compactmachines3-1.12.2-3.0.18-b278.jar       | None                                     |
	| LCHIJA | compactsolars        | 1.12.2-5.0.18.341        | CompactSolars-1.12.2-5.0.18.341-universal.jar | None                                     |
	| LCHIJA | controlling          | 3.0.10                   | Controlling-3.0.10.jar                        | None                                     |
	| LCHIJA | cookingforblockheads | 6.5.0                    | CookingForBlockheads_1.12.2-6.5.0.jar         | None                                     |
	| LCHIJA | craftingex           | 1.2.0                    | CraftingEX_1.12-v1.2.0.jar                    | None                                     |
	| LCHIJA | craftingtweaks       | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar               | None                                     |
	| LCHIJA | ctgui                | 1.0.0                    | CraftTweaker2-1.12-4.1.20.624.jar             | None                                     |
	| LCHIJA | crafttweakerjei      | 2.0.3                    | CraftTweaker2-1.12-4.1.20.624.jar             | None                                     |
	| LCHIJA | waila                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LCHIJA | mantle               | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCHIJA | tconstruct           | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
	| LCHIJA | p455w0rdslib         | 2.3.161                  | p455w0rdslib-1.12.2-2.3.161.jar               | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | mousetweaks          | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                 | None                                     |
	| LCHIJA | danknull             | 1.7.91                   | DankNull-1.12.2-1.7.91.jar                    | 644f38521a349310a5dae0239577dc7beebefaec |
	| LCHIJA | elevatorid           | 1.3.14                   | ElevatorMod-1.12.2-1.3.14.jar                 | None                                     |
	| LCHIJA | enchdesc             | 1.1.15                   | EnchantmentDescriptions-1.12.2-1.1.15.jar     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | enderstorage         | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | farmingforblockheads | 3.1.28                   | FarmingForBlockheads_1.12.2-3.1.28.jar        | None                                     |
	| LCHIJA | fastfurnace          | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                  | None                                     |
	| LCHIJA | fastleafdecay        | v14                      | FastLeafDecay-v14.jar                         | None                                     |
	| LCHIJA | flansmod             | 5.7.2                    | Flan's Mod-1.12.2-5.7.2.jar                   | None                                     |
	| LCHIJA | fluxnetworks         | 4.1.0                    | FluxNetworks-1.12.2-4.1.1.34.jar              | None                                     |
	| LCHIJA | storagedrawers       | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar               | None                                     |
	| LCHIJA | framedcompactdrawers | 1.2.7                    | framedcompactdrawers-1.2.7.jar                | None                                     |
	| LCHIJA | cfm                  | 6.3.1                    | furniture-6.3.1-1.12.2.jar                    | None                                     |
	| LCHIJA | gravestone           | 1.10.3                   | gravestone-1.10.3.jar                         | None                                     |
	| LCHIJA | hbm                  | hbm-1.4.0A-1.12.2        | hbm-1.4.1a.jar                                | None                                     |
	| LCHIJA | ic2cropplugin        | 1.1                      | IC2CropBreeding Plugin V1.12-1.1.jar          | None                                     |
	| LCHIJA | ic2magma             | 1.0 - MC 1.12.2          | ic2magma-1.0.jar                              | None                                     |
	| LCHIJA | industrialrenewal    | 0.21.6                   | IndustrialRenewal_1.12.2-0.21.6.jar           | None                                     |
	| LCHIJA | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironbackpacks        | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar             | None                                     |
	| LCHIJA | ironchest            | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| LCHIJA | journeymap           | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| LCHIJA | jeresources          | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar       | None                                     |
	| LCHIJA | malisiscore          | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                  | None                                     |
	| LCHIJA | malisisdoors         | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| LCHIJA | mcwbridges           | 1.0.4                    | mcw-bridges-1.0.4-mc1.12.2.jar                | None                                     |
	| LCHIJA | mcwdoors             | 1.0                      | mcw-doors-1.0.0-mc1.12.2.jar                  | None                                     |
	| LCHIJA | mcwroofs             | 1.0.2                    | mcw-roofs-1.0.2-mc1.12.2.jar                  | None                                     |
	| LCHIJA | mechapartspack       | 5.7.2                    | Mecha Parts-Content Pack-1.12.2-5.7.2.jar     | None                                     |
	| LCHIJA | minetraps            | 1.0.4                    | MineTraps-1.12.2-(v.1.0.4).jar                | None                                     |
	| LCHIJA | moartinkers          | 0.6.0                    | moartinkers-0.6.0.jar                         | None                                     |
	| LCHIJA | mob_grinding_utils   | 0.3.13                   | MobGrindingUtils-0.3.13.jar                   | None                                     |
	| LCHIJA | modernweaponspack    | 5.7.2                    | Modern Warfare-Content Pack-1.12.2-5.7.2.jar  | None                                     |
	| LCHIJA | mw                   | 0.4.4.6                  | mw_2.0-0.4.4.6_mc1.12.2.jar                   | None                                     |
	| LCHIJA | opencomputers        | 1.7.5.192                | OpenComputers-MC1.12.2-1.7.5.192.jar          | None                                     |
	| LCHIJA | omlib                | 3.1.4-249                | omlib-1.12.2-3.1.4-249.jar                    | None                                     |
	| LCHIJA | openmodularturrets   | 3.1.12-378               | openmodularturrets-1.12.2-3.1.12-378.jar      | None                                     |
	| LCHIJA | oreexcavation        | 1.4.150                  | OreExcavation-1.4.150.jar                     | None                                     |
	| LCHIJA | harvestcraft         | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zg.jar               | None                                     |
	| LCHIJA | placebo              | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                      | None                                     |
	| LCHIJA | railcraft            | 12.0.0                   | railcraft-12.0.0.jar                          | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | secretroomsmod       | 5.6.4                    | secretroomsmod-1.12.2-5.6.4.jar               | None                                     |
	| LCHIJA | simplepartspack      | 5.7.2                    | Simple Parts-Content Pack-1.12.2-5.7.2.jar    | None                                     |
	| LCHIJA | tcomplement          | 1.12.2-0.4.3             | TinkersComplement-1.12.2-0.4.3.jar            | None                                     |
	| LCHIJA | tinkersjei           | 1.2                      | tinkersjei-1.2.jar                            | None                                     |
	| LCHIJA | tinkersoc            | 0.6                      | tinkersoc-0.6.jar                             | None                                     |
	| LCHIJA | tinkertoolleveling   | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar           | None                                     |
	| LCHIJA | titanpack            | 5.7.2                    | Titan-Content Pack-1.12.2-5.7.2.jar           | None                                     |
	| LCHIJA | trapcraft            | 2.4.5                    | Trapcraft-1.12.2-2.4.5.jar                    | None                                     |
	| LCHIJA | wailaharvestability  | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar         | None                                     |
	| LCHIJA | wawla                | 2.6.275                  | Wawla-1.12.2-2.6.275.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | waystones            | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                    | None                                     |
	| LCHIJA | ww2pack              | 5.7.2                    | WW2-Content Pack-1.12.2-5.7.2.jar             | None                                     |
	| LCHIJA | xpbook               | v2.0                     | xptome-1.12.2-v2.0.jar                        | None                                     |
	| LCHIJA | trapexpansion        | 1.0.0                    | trapexpansion-1.0.0.jar                       | None                                     |
	| LCHIJA | mysticallib          | 1.12.2-1.9.0             | mysticallib-1.12.2-1.9.0.jar                  | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
weaponlib (mw_2.0-0.4.4.6_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleMelter (Enabled/Not Forced)
		- ModuleArmor (Enabled/Not Forced)
		- ModuleSteelworks (Enabled/Not Forced)
		- ChiselPlugin (Enabled/Not Forced)
		- ToolLevelingPlugin (Enabled/Not Forced)
		- Oredict (Enabled/Forced)

	AE2 Integration: IC2:ON, RC:ON, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:ON, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['abel1502'/1234, l='3 (Creative)', x=-2261.52, y=1.00, z=-728.08]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 26.20.100.7642
	OpenGlRenderer: Intel(R) UHD Graphics
	OpenGlVendor: Intel
	CpuCount: 12
[22:42:52] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# D:\Games\CurseForge\Minecraft\Instances\Military\crash-reports\crash-2021-02-28_22.42.51-server.txt
```

**Comment by Drillgon200** [comment]
Fixed.
