### ISSUE TITLE
Steam Turbine not working in one certain world????

### ISSUE THREAD

**Issue by churipputori** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#61]
I noticed that in my survival server the steam turbine was completely broken. Instead of it defaulting to steam and having a white turbine icon, the turbine icon is blank and putting in a Steam ID does absolutely nothing (not even move it to the second slot). After removing a few old mods, I tested it in a single player world and it worked perfectly fine. I tried it on the dedicated server, it didn't work, same mods n everything. I enabled every mod in single player, and it worked perfectly! I then just straight up renamed the world folder on the dedicated server so it would regenerate the world and enabled my mods, and boom! Perfectly working. So why is it that my actual world... doesn't work?

While testing the new world, I had realized something that didn't appear in any of the other tests. For some reason, the steam display on the boiler has a slightly glitched up temperature display of "373 C", which didn't appear in any of the other worlds. https://gyazo.com/01aa83590bccb30f0e37ec9cd29a2d1f
Could this be from some NBT tag that an old mod left over???

Checking the server logs, this error comes up:

`[23:57:27] [Server thread/ERROR] [FML]: A TileEntity type com.hbm.tileentity.machine.TileEntityMachineTurbine has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException: Null string not allowed
        at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_281]
        at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19) ~[gm.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:138) ~[fy.class:?]
        at com.hbm.tileentity.machine.TileEntityMachineTurbine.func_189515_b(TileEntityMachineTurbine.java:182) ~[TileEntityMachineTurbine.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:383) [aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:174) [aye.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:230) [on.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1007) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:691) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]`

Even worse, saving on a dedicated server causes the block to become completely corrupted, resulting in the server being unable to start back up until the block is deleted in MCEdit. 

Mod version is 1.4.0a-1.12.2, Forge version is 14.23.5.2854

**Comment by UFFR** [comment]
Minor note, the temperature display affects all NTM fluids in this port 
and is due to some issue regarding the temperature unit the fluid system 
and what unit they have been set as.

Meaning it was set with Celsius in mind, but Forge Fluids uses Kelvin, 
or vice versa, can't remember exactly. It shouldn't affect anything 
significant.

-- 
UFFR

**Comment by Drillgon200** [comment]
It's possible that FluidRegistry.getFluidName only works with the actual registered fluid and somehow you ended up with a non registered fluid in the turbine. I moved it to get the name from the fluid rather than the registry so that should fix that.
