### ISSUE TITLE
Game crash with the core reactor.

### ISSUE THREAD

**Issue by dhgameryt** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#65]
the server crashed when trying to enter.

crash report:
[crash-2021-03-22_20.20.26-server.txt](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/files/6185849/crash-2021-03-22_20.20.26-server.txt)

Description: Ticking block entity

java.lang.ClassCastException: com.hbm.tileentity.machine.TileEntityDummyFluidPort incompatible with com.hbm.tileentity.machine.TileEntityMachineReactorLarge
    at com.hbm.blocks.machine.ReactorCore.breakBlock(ReactorCore.java:32)
    at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:567)
    at net.minecraft.world.World.setBlockState(World.java:343)
    at net.minecraft.world.World.destroyBlock(World.java:419)
    at com.hbm.tileentity.machine.TileEntityDummy.update(TileEntityDummy.java:24)
    at net.minecraft.world.World.redirect$zzj000$tileEntityUpdate(World.java:4137)
    at net.minecraft.world.World.updateEntities(World.java:1838)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:823)

**Comment by Drillgon200** [comment]
I don't even know how this happens.

**Comment by dhgameryt** [comment]
NICE
