### ISSUE TITLE
Again, with the tileductbase crashing bulls***

### ISSUE THREAD

**Issue by TheForge129** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#8]
READ THE WHOLE ISSUE

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
	at net.minecraft.world.World.func_147448_a(World.java:1949)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:856)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_175625_s(World.java:2402)
	at com.hbm.tileentity.conductor.TileEntityFFDuctBaseMk2.joinOrMakeNetwork(TileEntityFFDuctBaseMk2.java:196)
	at com.hbm.tileentity.conductor.TileEntityFFDuctBaseMk2.onLoad(TileEntityFFDuctBaseMk2.java:110)
	at net.minecraft.world.World.func_175700_a(World.java:1924)
	at net.minecraft.world.World.func_147448_a(World.java:1951)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:856)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

old AND new worlds... I may be able to send you my mods so you can try to replicate them if you want
World was created in 1.3.4 and was played in 1.3.4... I may have lost a shitload of progress on a survival world because of this bs

**Comment by Drillgon200** [comment]
Just remove the erroring tile entities. There's literally nothing I can do about this without being able to replicate it, so please send the mods.

**Comment by TheForge129** [comment]
2 things.
i literally havent put any pipes in the world
also my modlist is:
hbm 1.3.4
securitycraft 1.8.19.3
small mods made by me in mcreator (notch apple recipes, rotten flesh to leather)
extra utilities 2 (unknown ver)
mysticallib
blockcraftery
chisel 1.0.2.45
infinite fluids 1.11 (compatible to 1.12.2) ver 1.2.0
filtered hopper 2.1.1 (on a quest to automate spent fuel reprocessing)
thutcore 5.21.0
thuttech 6.1.6
redstoneflux 2.1.1.1
mmdlib (unknown ver)
malisiscore 6.5.1
malisisdoors 7.3.0
cofhcore 4.6.6.1
ctm 1.0.2.31
atg 2.5.0
ezstorage 2.5.0
backpack 3.0.2
uppers 0.0.6
millenaire 8.1.0
weather2 2.6.10
xaeros world map 1.6.1
jei 4.15.0.293
crayfish gun mod 0.15.3
coroutil 1.2.37
vanilla builders extention 1.0.9
mumboredstone 0.33
redstone++ 1.3e
disenchanter 1.6
uncrafting table 1.8 beta 6
crayfish furniture 6.3.1
respawnable pets
optifine hd ultra e3
obfuscate 0.2.6
crayfish device mod 0.4.1
ghost's explosives
supertnt 1.0.1
sideslabs 1.1

**Comment by Drillgon200** [comment]
Wait you haven't even placed any fluid ducts in your world? They don't naturally generate, so something must be messing with them. Can you tell me what exact version of forge this is?

**Comment by TheForge129** [comment]
1.12.2-forge1.12.2-14.23.5.2847

**Comment by TheForge129** [comment]
@Drillgon200 1.12.2-forge1.12.2-14.23.5.2847

**Comment by TheForge129** [comment]
Doesn't seem to happen now, although that may because i'm getting a new crash for the ore acidizer

java.lang.RuntimeException: Slot 5 not in valid range - [0,5)
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:214)
	at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:73)
	at com.hbm.tileentity.machine.TileEntityMachineCrystallizer.getCycleCount(TileEntityMachineCrystallizer.java:245)
	at com.hbm.tileentity.machine.TileEntityMachineCrystallizer.func_73660_a(TileEntityMachineCrystallizer.java:77)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
probably just gonna downgrade to 1.3.3 to get rid of the acidizers

**Comment by Drillgon200** [comment]
Probably another one of those things where you have to break and replace them.

**Comment by TheForge129** [comment]
no longer happens, thank god

**Comment by TheForge129** [comment]
false alarm, still broken af

**Comment by Drillgon200** [comment]
Which issue? You should create a new issue for each crash type.

**Comment by TheForge129** [comment]
yeah good point, its the tileductbase
