### ISSUE TITLE
Placing a Waste Drum make the game crash since version 1.4.3

### ISSUE THREAD

**Issue by Devnary** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#81]
Placing in a single player new world :
```
[18:41:02] [Server thread/ERROR] [FML]: A TileEntity type com.hbm.tileentity.machine.TileEntityWasteDrum has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException: null
	at com.hbm.tileentity.machine.TileEntityWasteDrum.func_189515_b(TileEntityWasteDrum.java:52) ~[TileEntityWasteDrum.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:383) [aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:174) [aye.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:230) [on.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1007) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:446) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:372) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:579) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282-ea]
```
Placing in a server old world (from 1.4.1 to 1.4.3) :
```
[18:27:07] [Server thread/ERROR] [FML]: A TileEntity type com.hbm.tileentity.machine.TileEntityWasteDrum has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException: null
	at com.hbm.tileentity.machine.TileEntityWasteDrum.func_189515_b(TileEntityWasteDrum.java:52) ~[TileEntityWasteDrum.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:383) [aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:174) [aye.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:230) [on.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1007) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:446) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:579) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282-ea]
```

*and for fun*
```
[18:44:59] [Server thread/WARN] [FML]: HBM's Nuclear Tech Mod loaded a new chunk [21, 10] in dimension 0 (overworld) while populating chunk [21, 9], causing cascading worldgen lag.
[18:44:59] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config
```

**Comment by Drillgon200** [comment]
Fixed.
World gen thing isn't an error I'm going to fix, that's just a result of some NTM structures being larger than one chunk.
